# Generated by Django 3.1.5 on 2021-02-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='author_name',
            new_name='author',
        ),
    ]
