# Generated by Django 3.1.5 on 2021-02-02 09:35

import django.contrib.postgres.fields
from django.db import migrations, models
import restapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210201_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=restapi.models.get_init_list, size=None),
        ),
    ]
